#!/bin/sh
cd "${0%/*}"
exec node \
  --experimental-specifier-resolution=node \
  --input-type=module \
  --loader=ts-node/esm \
  --no-warnings \
  -e '
  import loadFunds from "./src/loadFunds"
  await loadFunds(...process.argv.slice(1))
  ' "$@"
